# Generated by Django 3.0.2 on 2020-01-24 15:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
                ('user_special', models.CharField(max_length=500)),
                ('user_share', models.BooleanField()),
                ('vehicle_plate', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_capacity', models.IntegerField()),
                ('vehicle_special', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('dest', models.CharField(max_length=100)),
                ('arrival', models.DateTimeField()),
                ('num_passenger', models.IntegerField()),
                ('sharable', models.BooleanField()),
                ('passenger_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='rideshare.User')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='rideshare.User')),
                ('sharer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sharer', to='rideshare.User')),
                ('user_special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to='rideshare.User')),
                ('vehicle_special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_request', to='rideshare.User')),
            ],
        ),
    ]
