# Generated by Django 3.0.2 on 2020-01-29 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger', to=settings.AUTH_USER_MODEL)),
                ('ride_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rideid', to='rideshare.app_ride')),
            ],
        ),
    ]
