# Generated by Django 2.2.9 on 2020-01-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='num_passenger',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='sharable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_share',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
