# Generated by Django 3.0.2 on 2020-01-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0002_auto_20200124_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
