# Generated by Django 3.0.2 on 2020-01-28 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rideshare', '0002_auto_20200124_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_share',
            new_name='will_drive',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='sharer',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='vehicle_special',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_special',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='ride',
            name='user_special',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_capacity',
            field=models.IntegerField(default=4),
        ),
    ]
