# Generated by Django 3.0.2 on 2020-01-28 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0003_remove_user_user_type'),
        ('rideshare', '0003_auto_20200128_0216'),
    ]

    operations = [
    ]
