# Generated by Django 3.0.2 on 2020-02-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0003_auto_20200129_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_passenger',
            name='party_size',
            field=models.IntegerField(default=0),
        ),
    ]
