# Generated by Django 3.0.2 on 2020-02-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0004_app_passenger_party_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_ride',
            name='remaining',
            field=models.IntegerField(default=4),
        ),
    ]
