# Generated by Django 3.0.2 on 2020-02-02 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0005_app_ride_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_passenger',
            name='party_size',
            field=models.IntegerField(default=0, verbose_name='Number of Passengers'),
        ),
        migrations.AlterField(
            model_name='app_ride',
            name='arrival',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Arrival Time'),
        ),
        migrations.AlterField(
            model_name='app_ride',
            name='dest',
            field=models.CharField(max_length=100, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='app_ride',
            name='num_passenger',
            field=models.IntegerField(default=0, verbose_name='Number of Passengers'),
        ),
        migrations.AlterField(
            model_name='app_ride',
            name='sharable',
            field=models.BooleanField(default=False, verbose_name='Share?'),
        ),
        migrations.AlterField(
            model_name='app_ride',
            name='user_special',
            field=models.CharField(blank=True, max_length=500, verbose_name='Special Request'),
        ),
        migrations.AlterField(
            model_name='app_ride',
            name='v_type',
            field=models.CharField(blank=True, max_length=500, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='Your Name'),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='vehicle_capacity',
            field=models.IntegerField(default=4, verbose_name='Vehicle Capacity'),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='vehicle_plate',
            field=models.CharField(max_length=100, verbose_name='Vehicle Plate Number'),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='vehicle_special',
            field=models.CharField(max_length=500, verbose_name='Vehicle Special Information'),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='vehicle_type',
            field=models.CharField(max_length=100, verbose_name='Vehicle Type'),
        ),
    ]
