# Generated by Django 3.0.2 on 2020-02-07 19:51

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0007_auto_20200207_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_ride',
            name='arrival',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)], verbose_name='Arrival Time'),
        ),
    ]
